name: Slack

on: 
  watch:
    types: [started]

jobs:
  celebrate:
    name: Celebrate
    runs-on: [ubuntu-latest]
    steps: 
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: | 
           {
            text: "GitHub Stargazer",
            blocks: [{
               "type": "section", 
               "text": {
                 "type": "mrkdwn",
                 "text": "✨New Star from *<${{github.event.sender.url}}|${{ github.actor }}>*!✨\n\n ${{github.event.repository.name}} now has *${{ github.event.repository.stargazers_count }}* stargazers!" 
                 },
               "accessory": {
                 "type": "image",
                 "image_url": "${{ github.event.sender.avatar_url }}",
                 "alt_text": "${{ github.actor }} avatar"
               } 
               }]
           }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() # P
     
 
