name: Slack

on: 
  watch:
    types: [started]

jobs:
  celebrate:
    name: Celebrate
    runs-on: [ubuntu-latest]
    steps: 
    - uses: 8398a7/action-slack@v2
      with:
        status: custom
        payload: | 
           {
            text: "GitHub Stargazer",
            blocks: [{
              "type": "section", 
              "text": {
                "type": "mrkdwn",
                "text": "**Woo!** <${{github.event.sender.url}}|${{ github.actor }}> just starred ${{github.event.repository.name}}! " 
                  }
                }
              ],  
            attachments: [{
              color: "#d4af37", 
              title: "✨New Star !✨", 
              text: "<${{github.event.sender.url}}|${{ github.actor }}> just starred ${{github.event.repository.name}}! Total stars: ${{ github.event.repository.stargazers_count }} " 
            }]
           }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() # P
     
 
